const KEY='qqMenuGitHubConfigV2';
const $=s=>document.querySelector(s);let store={storeName:'我的商品店',notice:'欢迎光临',categories:[{id:'cat1',name:'热卖商品'}],products:[]};
const cfg=()=>({owner:$('#owner').value.trim(),repo:$('#repo').value.trim(),branch:$('#branch').value.trim()||'main',token:$('#token').value.trim()});
function toast(msg,error=false){const t=$('#toast');t.textContent=msg;t.className='toast'+(error?' error':'');t.hidden=false;clearTimeout(window.__toast);window.__toast=setTimeout(()=>t.hidden=true,3200)}
function loadConfig(){try{const c=JSON.parse(localStorage.getItem(KEY)||'{}');for(const k of ['owner','repo','branch','token']) if(c[k]!=null) $('#'+k).value=c[k]}catch{}updateSiteLink()}
function saveConfig(){const c=cfg();if(!c.owner||!c.repo||!c.token)return toast('请填写 GitHub 用户名、仓库名和 Token',true);localStorage.setItem(KEY,JSON.stringify(c));$('#status').textContent='已保存配置';$('#status').className='status ok';updateSiteLink();toast('配置已保存')}
function updateSiteLink(){const c=cfg();if(c.owner&&c.repo){const url=c.repo===c.owner+'.github.io'?`https://${c.owner}.github.io/`:`https://${c.owner}.github.io/${c.repo}/`;$('#siteLink').href=url;$('#siteLink').textContent='打开顾客菜单';}else{$('#siteLink').href='#'}}
function headers(){return {'Accept':'application/vnd.github+json','Authorization':'Bearer '+cfg().token,'X-GitHub-Api-Version':'2026-03-10','Content-Type':'application/json'}}
async function api(path,opt={}){const r=await fetch('https://api.github.com'+path,{...opt,headers:{...headers(),...(opt.headers||{})}});let d={};try{d=await r.json()}catch{}if(!r.ok)throw new Error(d.message||('GitHub API '+r.status));return d}
async function getFile(path){return api(`/repos/${encodeURIComponent(cfg().owner)}/${encodeURIComponent(cfg().repo)}/contents/${path}?ref=${encodeURIComponent(cfg().branch)}`)}
function decodeBase64(s){const bin=atob(s.replace(/\n/g,''));const bytes=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)bytes[i]=bin.charCodeAt(i);return new TextDecoder().decode(bytes)}
function b64(bytes){const u8=bytes instanceof ArrayBuffer?new Uint8Array(bytes):bytes;let bin='';const chunk=0x8000;for(let i=0;i<u8.length;i+=chunk)bin+=String.fromCharCode(...u8.subarray(i,Math.min(i+chunk,u8.length)));return btoa(bin)}
async function putFile(path,bytes,message,sha){const body={message,content:b64(bytes),branch:cfg().branch};if(sha)body.sha=sha;return api(`/repos/${encodeURIComponent(cfg().owner)}/${encodeURIComponent(cfg().repo)}/contents/${path}`,{method:'PUT',body:JSON.stringify(body)})}
async function publishText(path,text,message){let sha=null;try{sha=(await getFile(path)).sha}catch(e){if(!String(e.message).includes('Not Found'))throw e}return putFile(path,new TextEncoder().encode(text),message,sha)}
async function loadRemote(){try{saveConfig();const f=await getFile('data/store.json');store=JSON.parse(decodeBase64(f.content));render();toast('已从 GitHub 读取当前店铺');$('#status').textContent='GitHub 已连接';$('#status').className='status ok'}catch(e){toast('读取失败：'+e.message,true)}}
function render(){$('#storeName').value=store.storeName||'';$('#notice').value=store.notice||'';renderCats();renderProducts()}
function renderCats(){const wrap=$('#categoryList');wrap.innerHTML='';for(const c of store.categories||[]){const row=document.createElement('div');row.className='category-item';const input=document.createElement('input');input.value=c.name;input.addEventListener('input',()=>{c.name=input.value});const del=document.createElement('button');del.className='danger';del.textContent='删除';del.onclick=()=>{if(store.products.some(p=>p.categoryId===c.id))return toast('该分类还有商品，请先移动/删除商品',true);store.categories=store.categories.filter(x=>x.id!==c.id);renderCats();renderProducts()};row.append(input,del);wrap.appendChild(row)}}
function renderProducts(){const wrap=$('#productList');wrap.innerHTML='';const tpl=$('#productTemplate');(store.products||[]).forEach((p,i)=>{const node=tpl.content.cloneNode(true);const root=node.querySelector('.product-edit');node.querySelector('.product-index').textContent=`商品 ${i+1}`;node.querySelector('.p-name').value=p.name||'';node.querySelector('.p-price').value=p.price??0;node.querySelector('.p-desc').value=p.desc||'';node.querySelector('.p-visible').checked=p.visible!==false;const sel=node.querySelector('.p-category');for(const c of store.categories||[]){const o=document.createElement('option');o.value=c.id;o.textContent=c.name;sel.appendChild(o)}sel.value=p.categoryId||store.categories?.[0]?.id||'';node.querySelector('.p-name').oninput=e=>p.name=e.target.value;node.querySelector('.p-price').oninput=e=>p.price=Number(e.target.value||0);node.querySelector('.p-desc').oninput=e=>p.desc=e.target.value;sel.onchange=e=>p.categoryId=e.target.value;node.querySelector('.p-visible').onchange=e=>p.visible=e.target.checked;node.querySelector('.delete-product').onclick=()=>{store.products=store.products.filter(x=>x.id!==p.id);renderProducts()};node.querySelector('.move-top').onclick=()=>{store.products=[p,...store.products.filter(x=>x.id!==p.id)];renderProducts()};node.querySelector('.p-images').onchange=e=>attachImages(p,e.target.files,root);renderImageRow(p,root);wrap.appendChild(node)})}
async function attachImages(p,files,root){for(const file of files){try{const out=await compressImage(file);const name='assets/products/'+p.id+'-'+Date.now()+'.webp';p.pending=p.pending||[];p.pending.push({path:name,bytes:out,preview:URL.createObjectURL(file)});renderImageRow(p,root)}catch(e){toast('图片处理失败：'+e.message,true)}}}
function renderImageRow(p,root){const row=root.querySelector('.image-row');row.innerHTML='';for(const u of (p.images||[])){const chip=document.createElement('div');chip.className='image-chip';const img=document.createElement('img');img.src=u;const b=document.createElement('button');b.textContent='×';b.onclick=()=>{p.images=p.images.filter(x=>x!==u);renderImageRow(p,root)};chip.append(img,b);row.appendChild(chip)}for(const u of (p.pending||[])){const chip=document.createElement('div');chip.className='image-chip';const img=document.createElement('img');img.src=u.preview;const b=document.createElement('button');b.textContent='×';b.onclick=()=>{p.pending=p.pending.filter(x=>x!==u);URL.revokeObjectURL(u.preview);renderImageRow(p,root)};chip.append(img,b);row.appendChild(chip)}}
function addCategory(){const id='cat'+crypto.randomUUID().replaceAll('-','').slice(0,10);store.categories.push({id,name:'新分类'});renderCats();renderProducts()}
function addProduct(){const id='p'+crypto.randomUUID().replaceAll('-','').slice(0,12);store.products.push({id,categoryId:store.categories?.[0]?.id||'',name:'新商品',price:0,desc:'',images:[],visible:true,pending:[]});renderProducts();window.scrollTo({top:document.body.scrollHeight,behavior:'smooth'})}
function compressImage(file){return new Promise((resolve,reject)=>{const img=new Image();img.onload=()=>{const max=1600;const scale=Math.min(1,max/Math.max(img.naturalWidth,img.naturalHeight));const c=document.createElement('canvas');c.width=Math.max(1,Math.round(img.naturalWidth*scale));c.height=Math.max(1,Math.round(img.naturalHeight*scale));const ctx=c.getContext('2d');ctx.drawImage(img,0,0,c.width,c.height);c.toBlob(blob=>blob?blob.arrayBuffer().then(resolve).catch(reject):reject(new Error('浏览器不支持图片压缩')),'image/webp',.82)};img.onerror=()=>reject(new Error('无法读取图片'));img.src=URL.createObjectURL(file)})}
async function publish(){try{saveStoreFields();const c=cfg();if(!c.owner||!c.repo||!c.token)throw new Error('请先保存 GitHub 配置');$('#publish').disabled=true;$('#publishText').textContent='正在上传图片和店铺数据…';let count=0;for(const p of store.products){for(const item of (p.pending||[])){await putFile(item.path,item.bytes,'上传商品图片 '+p.name,null);p.images.push(item.path.replaceAll(' ','%20'));count++}p.pending=[]}
  const clean=JSON.parse(JSON.stringify(store));for(const p of clean.products)p.pending=undefined;await publishText('data/store.json',JSON.stringify(clean,null,2),'更新店铺商品数据');
  toast(`发布成功：数据已更新${count?`，上传 ${count} 张图片`:''}`);$('#status').textContent='发布成功';$('#status').className='status ok';const url=c.repo===c.owner+'.github.io'?`https://${c.owner}.github.io/`:`https://${c.owner}.github.io/${c.repo}/`;$('#publishText').textContent='公开菜单：'+url;updateSiteLink();
}catch(e){toast('发布失败：'+e.message,true);$('#publishText').textContent='发布失败，请查看右下角提示。'}finally{$('#publish').disabled=false}}
function saveStoreFields(){store.storeName=$('#storeName').value.trim()||'我的商品店';store.notice=$('#notice').value}
$('#saveConfig').onclick=saveConfig;$('#loadRemote').onclick=loadRemote;$('#addCategory').onclick=addCategory;$('#addProduct').onclick=addProduct;$('#publish').onclick=publish;$('#storeName').oninput=()=>store.storeName=$('#storeName').value;$('#notice').oninput=()=>store.notice=$('#notice').value;loadConfig();render();
